version: "2.4"
services:
  app:
    build:
      context: .
      args:
        PORT: 5000
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=notasecret
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=project.settings.test
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/nomadbooks
      - FRONT_URL=https://nombadbooks.io
    volumes:
      - ./:/code
    working_dir: /code
    command: /app/scripts/run_tests.sh
  postgres:
    image: postgres:10.6
    environment:
      - POSTGRES_DB=nomadbooks
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
