version: "2.4"

services:
  django:
    build:
      context: .
    container_name: nomadbooks_django
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=notasecret
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=project.settings.base
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/nomadbooks
      - FRONT_URL=https://nombadbooks.io
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_SECRET_ACCESS_KEY=secret_access_key
      - AWS_STORAGE_BUCKET_NAME=bucket_name
    command: /app/manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
  postgres:
    image: postgres:10.6
    container_name: nomadbooks_postgres
    environment:
      - POSTGRES_DB=nomadbooks
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"