version: "2.4"

services:
  django:
    build:
      context: .
      target: dev
    mem_limit: 300m
    mem_reservation: 100m
    restart: always
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=notasecret
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=project.settings.test
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/nomadbooks
      - FRONT_URL=https://nombadbooks.io
    command: /app/scripts/run_tests.sh
  postgres:
    restart: always
    image: postgres:10.6
    environment:
      - POSTGRES_DB=nomadbooks
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres