version: "2.4"

services:
  django:
    build:
      context: .
      target: prod
    restart: always
    container_name: nomadbooks_django
    image: django
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=notasecret
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=project.settings.base
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/nomadbooks
      - FRONT_URL=https://nombadbooks.io
    ports:
      - "5000:5000"
  postgres:
    restart: always
    container_name: nomadbooks_postgres
    image: postgres:10.6
    environment:
      - POSTGRES_DB=nomadbooks
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
